from snakemake.utils import min_version

min_version("7.14.0")


configfile: "config/config.yaml"


if config["mosaicatcher_pipeline"] is False:

    docker_container = "docker://weber8thomas/ashleys-qc-pipeline:{version}".format(
        version=str(config["version"])
    )

    containerized: docker_container


include: "rules/common.smk"


include: "rules/aggregate_fct.smk"


include: "rules/rules.smk"


include: "rules/gc.smk"


include: "rules/count.smk"


include: "rules/multiqc.smk"


if config["mosaicatcher_pipeline"] is False:

    include: "rules/external_data.smk"


if config["list_commands"] is False:

    rule all:
        input:
            get_final_output(),


    if config["email"]:

        onsuccess:
            onsuccess_fct(log)

        onerror:
            onerror_fct(log)
