# Default runtime profile for TM infrastructure / D3 compute server

SRC_PATH: /scratch/bioinf/users/pebert/data_sources/strandseq/HG00096_hgsvc_ilnxs-80pe_sseq/
INPUT_PATH: /scratch/bioinf/users/eimer/pipeline/input/
OUTPUT_PATH: /scratch/bioinf/users/eimer/pipeline/output/
reference: /scratch/bioinf/users/eimer/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz.bwt

cores: 48
latency-wait: 5
keep-going: True
rerun-incomplete: True
restart-times: 0
