name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - weber8thomas
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Mosaicatcher-pipeline Version
      description: What version of ashleys-qc-pipeline are you running?
      options:
        - "1.5.1 (Default)"
        - "1.4.1"
        - "1.4"
        - "1.3"
        - "1.2"
        - "1.1"
        - "1.0"
    validations:
      required: true
  - type: textarea
    id: cmd
    attributes:
      label: Command used
      description: Please copy and paste the command used to launch the pipeline.
      render: shell
  - type: dropdown
    id: mode_of_execution
    attributes:
      label: How did you run the pipeline?
      options:
        - Conda only
        - Conda + Singularity
    validations:
      required: true
  - type: textarea
    id: execution_type
    attributes:
      label: What did you use to run the pipeline? (local execution, HPC, cloud)
      description: |
        Please give us some details
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Pipeline configuration file
      description: Please copy and paste the configuration file used.
      render: YAML
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
