default-resources:
  mem_mb: 1000
  runtime: 30

set-resources:
  bwa_index:
    runtime: 60
    mem_mb: 2000
    cpus_per_task: 1
    threads: 1
  bwa_strandseq_to_reference_alignment:
    runtime: 60
    mem_mb: 2000
    cpus_per_task: 1
    threads: 1
