## Data location - MUST BE AN ABSOULTE PATH (due to snakemake-symlink issues) - PLEASE MODIFY IT
input_bam_location: ".tests/data_CHR17"
# Reference genome used by BWA to map FASTQ files
# reference: .tests/external_data/chr21.fna

reference: "hg38"

references_data:
  "hg38":
    reference_fasta: ".tests/external_data/chr17.fa.gz"
  "hg19":
    reference_fasta: "workflow/data/ref_genomes/hg19.fa"
  "T2T":
    reference_fasta: "workflow/data/ref_genomes/T2T.fa"

# Enable / Disable download of external files (1000G SNV & Fasta ref genome)
dl_external_files: False
# Overwrite ASHLEYS PREDICTIONS
use_light_data: True

############################################################################
#                          EXPERIMENTAL PARAMETERS
############################################################################
# Boolean parameters
## Is the pipeline called used as a submodule in mosaicatcher-pipeline?
mosaicatcher_pipeline: False
## Enable/Disable hand selection through Jupyter Notebook
hand_selection: False

# Window size used by mosaic binning algorithm
window: 100000

# Chromosomes list to process
chromosomes:
  - chr17
