name: Example Workflow

on:
  push:
    branches:
      - "**"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world! My first GitHub Actions workflow."

      - name: Run a multi-line script
        run: |
          echo "This is a multi-line script."
          echo "You can add more commands here."
          echo "Each command is run in the shell."
