name: Workflow checks

on:
  push:
    branches:
      - master
      - smk_wf_catalog

jobs:
  # WORK
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: .
          snakefile: ./Snakefile
          stagein: "mkdir -p .tests/data"
          args: "--lint"
  # Testing:
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - Linting
  #   #   - Formatting
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Testing data
  #       uses: snakemake/snakemake-github-action@v1.23.0
  #       with:
  #         directory: .
  #         snakefile: ./Snakefile
  #         stagein: " mamba env remove -n snakemake && mamba create -y -n snakemake -c conda-forge -c bioconda snakemake pandas pysam tqdm imagemagick && source activate snakemake"
  #         args: "--cores 2 --configfile .tests/config/test_config.yaml  --use-conda"
