name: ashleys-qc-pipeline workflow checks

on:
  push:
    branches:
      - dev

jobs:
  # WORK
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          # stagein: "mamba env remove -n snakemake && mamba create -y -n snakemake -c conda-forge -c bioconda unzip snakemake pandas pysam tqdm imagemagick && source activate snakemake && ls -l && pwd"
          args: "--lint --config ashleys_pipeline=True"
  Testing_ashleys:
    runs-on: ubuntu-latest
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Testing data
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1 --use-conda --configfile .tests/config/simple_config.yaml --conda-frontend mamba -p --verbose --debug"
      - name: Testing report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--cores 1 --use-conda --configfile .tests/config/simple_config.yaml --conda-frontend mamba --report report.zip"

  Testing_ashleys_GC_enabled:
    runs-on: ubuntu-latest
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Testing data
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1 --use-conda --config reference=hg38 use_light_data=True chromosomes=[chr17] GC_analysis=True --conda-frontend mamba -p --verbose --debug"
      - name: Testing report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--cores 1 --use-conda --config reference=hg38 use_light_data=True chromosomes=[chr17] GC_analysis=True --conda-frontend mamba --report report.zip"
  Testing_ashleys_hg38:
    runs-on: ubuntu-latest
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Testing data
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1 --use-conda --config reference=hg38 use_light_data=True chromosomes=[chr17] --conda-frontend mamba -p --verbose --debug"
      - name: Testing report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--cores 1 --use-conda --config reference=hg38 use_light_data=True chromosomes=[chr17] --conda-frontend mamba --report report.zip"
  Testing_ashleys_hg19:
    runs-on: ubuntu-latest
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Testing data
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1 --use-conda --config reference=hg19 use_light_data=True chromosomes=[chr17] --conda-frontend mamba -p --verbose --debug"
      - name: Testing report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--cores 1 --use-conda --config reference=hg19 use_light_data=True chromosomes=[chr17] --conda-frontend mamba --report report.zip"
  Testing_ashleys_T2T:
    runs-on: ubuntu-latest
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Testing data
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1 --use-conda --config reference=T2T use_light_data=True chromosomes=[chr17] --conda-frontend mamba -p --verbose --debug"
      - name: Testing report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--cores 1 --use-conda --config reference=T2T use_light_data=True chromosomes=[chr17] --conda-frontend mamba --report report.zip"
  Testing_jub_nb:
    runs-on: ubuntu-latest
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Testing data
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1 --use-conda --configfile .tests/config/simple_config.yaml --config hand_selection=True --conda-frontend mamba -p --verbose --debug"
      - name: Testing report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--cores 1 --use-conda --configfile .tests/config/simple_config.yaml --config hand_selection=True --conda-frontend mamba --report report.zip"
